version: '3.8'

services:
  account-service:
    build: ./account-service
    ports:
      - "8081:8081"

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"

  coordinator-service:
    build: ./coordinator-service
    ports:
      - "8080:8080"
    depends_on:
      - account-service
      - order-service
